openapi: 3.0.0
info:
  title: Vendors
  description: >-
    An invoice is a bill of sale for goods or services provided by a vendor.
    This API provides methods to create, update, or delete invoice vendors.
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: invoice
  - name: invoice > vendors
paths:
  /invoice/vendors:
    get:
      tags:
        - invoice > vendors
      summary: Retrieves an existing vendor.
      description: >-
        Gets an existing vendor. Note: If authenticating with a Company access
        token the API will return all vendors associated with a specific entity.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: limit
          in: query
          schema:
            type: string
          description: >-
            The maximum number of items to be returned in a  response. The
            default is 25 and cannot exceed 1000.
          example: <integer>
        - name: offset
          in: query
          schema:
            type: string
          description: >-
            Specifies the starting point for the next query when iterating
            through the collection response.  Use with paged collections of
            resources.
          example: <string>
        - name: sortDirection
          in: query
          schema:
            type: string
          description: ascending or descending, The default value will be ascending.
          example: <string>
        - name: sortBy
          in: query
          schema:
            type: string
          description: >-
            Field you need to the results to be sorted by. Vendor Name will be
            made default if no value is sent. Only fields that are added to the
            vendor form can be used here. Fields have to be specified by name as
            specified in Doc.
          example: <string>
        - name: searchType
          in: query
          schema:
            type: string
          description: >-
            Applies for the entire given search parameters. The default value is
            exact. Supported values: exact, begins, contains, ends
          example: <string>
        - name: vendorCode
          in: query
          schema:
            type: string
          description: Vendor Code to be searched
          example: <string>
        - name: vendorName
          in: query
          schema:
            type: string
          description: Vendor Name to be searched
          example: <string>
        - name: taxID
          in: query
          schema:
            type: string
          description: Tax ID to be searched
          example: <string>
        - name: buyerAccountNumber
          in: query
          schema:
            type: string
          description: Buyer Account Number to be searched
          example: <string>
        - name: addressCode
          in: query
          schema:
            type: string
          description: Address Code to be searched
          example: <string>
        - name: paymentMethodType
          in: query
          schema:
            type: string
          description: >-
            Payment Method Type to be searched. Valid values are ACH, CARD,
            CHECK, CLIENT, PAYPVD, VCHER, WIRE
          example: <string>
        - name: address1
          in: query
          schema:
            type: string
          description: Address 1 to be searched
          example: <string>
        - name: address2
          in: query
          schema:
            type: string
          description: Address 2 to be searched
          example: <string>
        - name: address3
          in: query
          schema:
            type: string
          description: Address 3 to be searched
          example: <string>
        - name: city
          in: query
          schema:
            type: string
          description: City to be searched
          example: <string>
        - name: state
          in: query
          schema:
            type: string
          description: State to be searched
          example: <string>
        - name: postalCode
          in: query
          schema:
            type: string
          description: Postal Code to be searched
          example: <string>
        - name: approved
          in: query
          schema:
            type: string
          description: Find Approved/Un Approved Vendors , True/False
          example: <string>
        - name: country
          in: query
          schema:
            type: string
          description: Country to be searched
          example: <string>
        - name: custom1
          in: query
          schema:
            type: string
          description: Custom 1 to be searched
          example: <string>
        - name: custom2
          in: query
          schema:
            type: string
          description: Custom 2 to be searched
          example: <string>
        - name: custom3
          in: query
          schema:
            type: string
          description: Custom 3 to be searched
          example: <string>
        - name: custom4
          in: query
          schema:
            type: string
          description: Custom 4 to be searched
          example: <string>
        - name: custom5
          in: query
          schema:
            type: string
          description: Custom 5 to be searched
          example: <string>
        - name: custom6
          in: query
          schema:
            type: string
          description: Custom 6 to be searched
          example: <string>
        - name: custom7
          in: query
          schema:
            type: string
          description: Custom 7 to be searched
          example: <string>
        - name: custom8
          in: query
          schema:
            type: string
          description: Custom 8 to be searched
          example: <string>
        - name: custom9
          in: query
          schema:
            type: string
          description: Custom 9 to be searched
          example: <string>
        - name: custom10
          in: query
          schema:
            type: string
          description: Custom 10 to be searched
          example: <string>
        - name: custom11
          in: query
          schema:
            type: string
          description: Custom 11 to be searched
          example: <string>
        - name: custom12
          in: query
          schema:
            type: string
          description: Custom 12 to be searched
          example: <string>
        - name: custom13
          in: query
          schema:
            type: string
          description: Custom 13 to be searched
          example: <string>
        - name: custom14
          in: query
          schema:
            type: string
          description: Custom 14 to be searched
          example: <string>
        - name: custom15
          in: query
          schema:
            type: string
          description: Custom 15 to be searched
          example: <string>
        - name: custom16
          in: query
          schema:
            type: string
          description: Custom 16 to be searched
          example: <string>
        - name: custom17
          in: query
          schema:
            type: string
          description: Custom 17 to be searched
          example: <string>
        - name: custom18
          in: query
          schema:
            type: string
          description: Custom 18 to be searched
          example: <string>
        - name: custom19
          in: query
          schema:
            type: string
          description: Custom 19 to be searched
          example: <string>
        - name: custom20
          in: query
          schema:
            type: string
          description: Custom 20 to be searched
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
    post:
      tags:
        - invoice > vendors
      summary: Creates new vendors.
      description: Creates a new vendor and returns the status of creation.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Message: <string>
    put:
      tags:
        - invoice > vendors
      summary: Manages existing vendors.
      description: Updates existing vendors and returns the update status.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Message: <string>
    delete:
      tags:
        - invoice > vendors
      summary: Deletes a vendor.
      description: Deletes a vendor by Vendor Code and Address Code.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: vendorCode
          in: query
          schema:
            type: string
          description: (Required) Vendor Code to be deleted
          example: <string>
        - name: addressCode
          in: query
          schema:
            type: string
          description: (Required) Address Code to be deleted
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Vendor:
                  AddressCode: <string>
                  CountryCode: <string>
                  VendorCode: <string>
                  AccountNumber: <string>
                  Address1: <string>
                  Address2: <string>
                  Address3: <string>
                  AddressImportSyncID: <string>
                  Approved: <string>
                  City: <string>
                  ContactEmail: <string>
                  ContactFirstName: <string>
                  ContactLastName: <string>
                  ContactPhoneNumber: <string>
                  Country: <string>
                  CurrencyCode: <string>
                  Custom1: <string>
                  Custom10: <string>
                  Custom11: <string>
                  Custom12: <string>
                  Custom13: <string>
                  Custom14: <string>
                  Custom15: <string>
                  Custom16: <string>
                  Custom17: <string>
                  Custom18: <string>
                  Custom19: <string>
                  Custom2: <string>
                  Custom20: <string>
                  Custom3: <string>
                  Custom4: <string>
                  Custom5: <string>
                  Custom6: <string>
                  Custom7: <string>
                  Custom8: <string>
                  Custom9: <string>
                  DefaultEmployeeID: <string>
                  DefaultExpenseTypeName: <string>
                  DiscountPercentage: <string>
                  DiscountTermsDays: <string>
                  ID: <string>
                  IsLineItemVatIncld: <string>
                  IsVisibleForContentExtraction: <string>
                  PaymentMethodType: <string>
                  PaymentTerms: <string>
                  PostalCode: <string>
                  ProvincialTaxID: <string>
                  PurchaseOrderContactEmail: <string>
                  PurchaseOrderContactFirstName: <string>
                  PurchaseOrderContactLastName: <string>
                  PurchaseOrderContactPhoneNumber: <string>
                  ShippingMethod: <string>
                  ShippingTerms: <string>
                  State: <string>
                  StatusList:
                    Code: <integer>
                    Message: <string>
                    RecordNumber: <integer>
                    Type: <string>
                  TaxID: <string>
                  TaxType: <string>
                  URI: <string>
                  VendorBankList:
                    AccountNumber: <string>
                    AccountType: <string>
                    AddressCode: <string>
                    BankCode: <string>
                    BankName: <string>
                    BranchCode: <string>
                    BranchLocation: <string>
                    CountryCode: <string>
                    CurrencyAlphaCode: <string>
                    ID: <string>
                    IsActive: <string>
                    NameOnAccount: <string>
                    RoutingNumber: <string>
                    StatusList:
                      Code: <integer>
                      Message: <string>
                      RecordNumber: <integer>
                      Type: <string>
                    TransType: <string>
                    URI: <string>
                    VendorCode: <string>
                  VendorFormName: <string>
                  VendorGroupList:
                    - <string>
                    - <string>
                  VendorName: <string>
                  VoucherNotes: <string>
                NextPage: <string>
                RequestRunSummary: <string>
                TotalCount: <integer>
                Items: {}
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Message: <string>
